fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                product:
                    properties:
                        title: ~
                        description: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Product
                        provider: ~
                        finder: ~
                variant:
                    properties:
                        color: ~
                        price: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Variant
                        provider: ~
                        finder: ~