# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        product_index:
            settings:
                index:
                    analysis:
                        analyzer:
                            text_analyzer:
                                type: snowball
                                language: English
            types:
                product:
                    properties:
                        title: { boost: 2}
                        description: { analyzer: text_analyzer }
                        variants:
                            type: object
                            properties:
                                color: ~
                                price:
                                    type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\Product
                        provider: ~
                        finder: ~
                        repository: App\Repository\SearchRepository\ProductSearchRepository
